=== patrodyne/hisrc-basicjaxb/higher/tests/swing/src/main/resources/PurchaseOrder.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema
	targetNamespace="http://example.org/PurchaseOrder"
	xmlns:tns="http://example.org/PurchaseOrder"
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:bi="http://jvnet.org/basicjaxb/xjc/beaninfo"
	xmlns:jaxb="https://jakarta.ee/xml/ns/jaxb"
	jaxb:version="3.0"
	jaxb:extensionBindingPrefixes="bi"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation=
		"http://jvnet.org/basicjaxb/xjc/beaninfo ../../../../../../src/test/resources/org/jvnet/basicjaxb/xjc/beaninfo.xsd"
>

	<!-- Global annotation. -->
	<xs:annotation>
		<xs:documentation xml:lang="en">
			Purchase order schema for Example.org.
			Copyright 2000 Example.org. All rights reserved.
		</xs:documentation>
	</xs:annotation>

	<!-- Top element(s) for element references. -->
	<xs:element name="Comment" type="xs:string">
		<xs:annotation>
			<xs:appinfo>
				<bi:property alignment="LEFT" minWidth="30">
					<displayName>Observation</displayName>
					<description>A remark, or statement based on what one has noticed.</description>
				</bi:property>
			</xs:appinfo>
		</xs:annotation>
	</xs:element>

	<!-- Top element(s) with anonymous complex type become XmlRootElement(s). -->
	<xs:element name="PurchaseOrder">
		<xs:annotation>
			<xs:appinfo>
				<bi:bean>
					<displayName>Purchase Order</displayName>
					<description>A document issued by a buyer to a seller, indicating types, quantities, and prices for products.</description>
				</bi:bean>
			</xs:appinfo>
		</xs:annotation>
        <xs:complexType>
			<xs:sequence>
				<xs:element name="shipTo" type="tns:USAddress" />
				<xs:element name="billTo" type="tns:USAddress" />
				<xs:element ref="tns:Comment" minOccurs="0" />
				<xs:element name="items" type="tns:Items" />
				<xs:element name="payments">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="payment" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:decimal">
											<xs:attribute name="paymentDate" type="xs:date" />
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="credits" type="tns:Credit" maxOccurs="unbounded" minOccurs="0" />
			</xs:sequence>
			<xs:attribute name="orderDate" type="xs:date" />
			<xs:attribute name="complete" type="xs:boolean"></xs:attribute>
		</xs:complexType>
    </xs:element>

	<xs:complexType name="USAddress">
		<xs:sequence>
			<xs:element name="name" type="xs:string" />
			<xs:element name="street" type="xs:string" />
			<xs:element name="city" type="xs:string" />
			<xs:element name="state" type="xs:string" />
			<xs:element name="zip" type="xs:decimal" />
		</xs:sequence>
		<xs:attribute name="country" type="xs:NMTOKEN" fixed="US" />
	</xs:complexType>

	<xs:complexType name="Items">
		<xs:sequence>
			<xs:element name="item" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="productName" type="xs:string" />
						<xs:element name="quantity">
							<xs:simpleType>
								<xs:restriction base="xs:positiveInteger">
									<xs:maxExclusive value="100" />
								</xs:restriction>
							</xs:simpleType>
						</xs:element>
						<xs:element name="USPrice" type="xs:decimal">
							<xs:annotation>
								<xs:appinfo>
									<bi:property>
										<readMethodName>getUSPrice</readMethodName>
										<writeMethodName>setUSPrice</writeMethodName>
									</bi:property>
								</xs:appinfo>
							</xs:annotation>
						</xs:element>
						<xs:element ref="tns:Comment" minOccurs="0" />
						<xs:element name="shipDate" type="xs:date" minOccurs="0" />
					</xs:sequence>
					<xs:attribute name="partNum" type="tns:SKU" use="required" />
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<!-- Stock Keeping Unit, a code for identifying products -->
	<xs:simpleType name="SKU">
		<xs:restriction base="xs:string">
			<xs:pattern value="\d{3}-[A-Z]{2}" />
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="Credit">
		<xs:attribute name="amount" type="xs:double"/>
		<xs:attribute name="reason" type="xs:string"/>
	</xs:complexType>

</xs:schema>
<!-- vi:set tabstop=4 hardtabs=4 shiftwidth=4: -->

=== patrodyne/hisrc-basicjaxb/higher/tests/swing/src/test/samples/PurchaseOrder02.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<po:PurchaseOrder orderDate="2025-01-28-05:00" complete="true"
	xmlns:po="http://example.org/PurchaseOrder"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://example.org/PurchaseOrder ../../main/resources/PurchaseOrder.xsd"
>
    <shipTo country="US">
        <name>Donna D. Perez</name>
        <street>106 Sixth Rd</street>
        <city>Dayton</city>
        <state>AL</state>
        <zip>31465</zip>
    </shipTo>
    <billTo country="US">
        <name>Donna D. Perez</name>
        <street>106 Sixth Rd</street>
        <city>Dayton</city>
        <state>AL</state>
        <zip>31465</zip>
    </billTo>
    <po:Comment>A hospital battled since any james.</po:Comment>
    <items>
        <item partNum="795-AN">
            <productName>cooking</productName>
            <picture>üç≥</picture>
            <quantity>2</quantity>
            <USPrice>63.40</USPrice>
            <po:Comment>One facilities balanced.</po:Comment>
            <shipDate>2025-01-31-05:00</shipDate>
        </item>
        <item partNum="824-AQ">
            <productName>fish cake with swirl design</productName>
            <picture>üç•</picture>
            <quantity>1</quantity>
            <USPrice>52.93</USPrice>
            <po:Comment>The motorcycle met.</po:Comment>
            <shipDate>2025-02-26-05:00</shipDate>
        </item>
    </items>
    <payments total="116.33">
        <payment paymentDate="2025-01-31-05:00">116.33</payment>
    </payments>
    <credits amount="17.45" reason="One bonsai toured."/>
</po:PurchaseOrder>

=== patrodyne/hisrc-basicjaxb/higher/tests/swing/src/test/samples/PurchaseOrder01.xml
<po:PurchaseOrder orderDate="1999-05-20" complete="false"
	xmlns:po="http://example.org/PurchaseOrder"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://example.org/PurchaseOrder ../../main/resources/PurchaseOrder.xsd"
>
	<shipTo country="US">
		<name>Alice Smith</name>
		<street>123 Maple Street</street>
		<city>Mill Valley</city>
		<state>CA</state>
		<zip>90952</zip>
	</shipTo>
	<billTo country="US">
		<name>Robert Smith</name>
		<street>8 Oak Avenue</street>
		<city>Old Town</city>
		<state>PA</state>
		<zip>95819</zip>
	</billTo>
	<po:Comment>Hurry, my lawn is going wild!</po:Comment>
	<items>
		<item partNum="872-AA">
			<productName>Lawnmower</productName>
			<quantity>1</quantity>
			<USPrice>148.95</USPrice>
			<po:Comment>Confirm this is electric</po:Comment>
		</item>
		<item partNum="926-AA">
			<productName>Baby Monitor</productName>
			<quantity>1</quantity>
			<USPrice>39.98</USPrice>
			<shipDate>1999-10-21</shipDate>
		</item>
	</items>
	<payments total="39.98">
		<payment paymentDate="1999-10-21">5.00</payment>
		<payment paymentDate="1999-10-22">10.00</payment>
		<payment paymentDate="1999-10-23">24.98</payment>
	</payments>
	<credits amount="5.00" reason="Promo: MAY99" />
	<credits amount="10.00" reason="Promo: OCT99" />
</po:PurchaseOrder>

=== patrodyne/hisrc-basicjaxb/higher/tests/swing/src/test/samples/PurchaseOrder03.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<po:PurchaseOrder orderDate="2024-09-01-04:00" complete="true"
	xmlns:po="http://example.org/PurchaseOrder"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://example.org/PurchaseOrder ../../main/resources/PurchaseOrder.xsd"
>
    <shipTo country="US">
        <name>Robert E. Adams</name>
        <street>628 Eighth Rd</street>
        <city>Milford</city>
        <state>DE</state>
        <zip>11657</zip>
    </shipTo>
    <billTo country="US">
        <name>Robert E. Adams</name>
        <street>628 Eighth Rd</street>
        <city>Milford</city>
        <state>DE</state>
        <zip>11657</zip>
    </billTo>
    <po:Comment>One hair headed below some drill.</po:Comment>
    <items>
        <item partNum="859-AZ">
            <productName>peach</productName>
            <picture>üçë</picture>
            <quantity>3</quantity>
            <USPrice>70.97</USPrice>
            <po:Comment>One angora delighted.</po:Comment>
            <shipDate>2024-09-06-04:00</shipDate>
        </item>
        <item partNum="812-AE">
            <productName>cookie</productName>
            <picture>üç™</picture>
            <quantity>1</quantity>
            <USPrice>69.02</USPrice>
            <po:Comment>One latex squealed.</po:Comment>
            <shipDate>2024-09-27-04:00</shipDate>
        </item>
    </items>
    <payments total="139.99">
        <payment paymentDate="2024-09-20-04:00">139.99</payment>
    </payments>
    <credits amount="21.00" reason="A leg understood."/>
</po:PurchaseOrder>
