=== patrodyne/hisrc-basicjaxb/higher/assembly/samples/datamap/src/main/resources/datamap.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified"
	targetNamespace="urn:example.org:datamap"
	xmlns:tns="urn:example.org:datamap"
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
>
	<xs:element name="employee" >
		<xs:complexType>
			<xs:sequence>
				<xs:element name="dataMap">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="entry" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="key" minOccurs="0" type="xs:string"/>
										<xs:element name="value" minOccurs="0" type="xs:anyType"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="value" type="xs:string" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== patrodyne/hisrc-basicjaxb/higher/assembly/samples/datamap/src/test/samples/employee.xml
<?xml version="1.0" encoding="UTF-8"?>
<employee
	xmlns="urn:example.org:datamap"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="urn:example.org:datamap ../../main/resources/datamap.xsd"
>
	<dataMap>
		<entry>
			<key>Name</key>
			<value>Rosie the Riveter</value>
		</entry>
		<entry>
			<key>Position</key>
			<value>Welder</value>
		</entry>
	</dataMap>
	<value>Exceptional</value>
</employee>
